version: '3'

services:

  mariadb:
    build: docker/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'crms'
    ports:
      - 3306:3306

  mariadb_ht:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'crms'
    ports:
      - 3307:3306

  test:
    build: .
    volumes:
      - .:/htapps/babel/crms
    environment:
      - SDRROOT=/htapps/babel
      - CRMS_DB_HOST=mariadb
      - CRMS_DB_HOST_DEVELOPMENT=mariadb
      - CRMS_HT_DB_HOST=mariadb_ht
    depends_on:
      - mariadb
      - mariadb_ht
    command: scripts/test.sh
