---

x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:

  mariadb:
    build: docker/db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  mariadb_ht:
    image: ghcr.io/hathitrust/db-image:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3307:3306
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  test:
    build: .
    volumes:
      - .:/htapps/babel/crms
    environment:
      - SDRROOT=/htapps/babel
      - CRMS_DB_HOST=mariadb
      #- CRMS_DB_HOST_DEVELOPMENT=mariadb
      - CRMS_HT_DB_HOST=mariadb_ht
      # pass through info needed by coveralls uploader
      - GITHUB_TOKEN
      - GITHUB_RUN_ID
      - GITHUB_EVENT_TOKEN
      - GITHUB_EVENT_PATH
      - GITHUB_SHA
      - GITHUB_REF
      - GITHUB_ACTIONS
    depends_on:
      mariadb: *healthy
      mariadb_ht: *healthy
    command: scripts/test.sh
