#!/usr/bin/perl

my ($root_dir);
BEGIN 
{ 
  $root_dir = $ENV{'DLXSROOT'};
  $root_dir = $ENV{'SDRROOT'} unless $root_dir;
}

use strict;
use CGI;
use CRMS;
use CRI;
use JSON::XS;

my $cgi = new CGI;
my $sys = $cgi->param('sys') || 'crms';
my $pdb = $cgi->param('pdb');
my $tdb = $cgi->param('tdb');
my $crms = CRMS->new(cgi     => $cgi,
                     sys     => $sys,
                     pdb     => $pdb,
                     tdb     => $tdb);

my $cri = CRI->new(crms => $crms);
my $id = $cgi->param('id');
my $data = $cri->GetCRIInfo($id) || '';
my $json = JSON::XS->new->encode($data);
print $cgi->header(-type => 'application/json', -charset => 'utf-8');
print $json;
