#!/usr/bin/perl

use strict;
use FindBin;
use lib $FindBin::Bin;
use CGI;
use CRMS;
use CRI;
use JSON::XS;

my $cgi = new CGI;
my $sys = $cgi->param('sys') || 'crms';
my $crms = CRMS->new(cgi => $cgi,
                     sys => $sys);
my $cri = CRI->new(crms => $crms);
my $id = $cgi->param('id');
my $data = $cri->GetCRIInfo($id) || '';
my $json = JSON::XS->new->encode($data);
print $cgi->header(-type => 'application/json', -charset => 'utf-8');
print $json;
