#!/usr/bin/perl

my ($root_dir);
BEGIN 
{ 
  $root_dir = $ENV{'DLXSROOT'};
  $root_dir = $ENV{'SDRROOT'} unless $root_dir;
}

use strict;
use CGI;
use CRMS;
use JSON::XS;
use Graph;
my $cgi  = new CGI;
my $sys =  $cgi->param('sys') || 'crms';
my $pdb = $cgi->param('pdb');
my $tdb = $cgi->param('tdb');
my $crms = CRMS->new(cgi     => $cgi,
                     sys     => $sys,
                     pdb     => $pdb,
                     tdb     => $tdb);

my $type = $cgi->param('type');
my $data = '';
my $c = $cgi->param('c'); # Class or cumulative
my $year = $cgi->param('y');
my $percent = $cgi->param('percent');
if ($type eq 'graph')
{
  if ($c == 0) { $data = Graph::CreateExportGraph($crms); }
  elsif ($c == 1) { $data = Graph::CreateExportBreakdownGraph($crms); }
  elsif ($c == 2) { $data = Graph::CreateExportsPieChart($crms); }
  elsif ($c == 3) { $data = Graph::CreateDeterminationsBreakdownGraph($crms); }
  elsif ($c == 4) { $data = Graph::CreateCandidatesGraph($crms); }
  elsif ($c == 5) { $data = Graph::CreateCountriesGraph($crms); }
  elsif ($c == 6) { $data = Graph::CreateUndGraph($crms); }
  elsif ($c == 7) { $data = Graph::CreateNamespaceGraph($crms); }
  elsif ($c == 9) { $data = Graph::CreateReviewInstitutionGraph($crms); }
  elsif ($c == 10)
  {
    my $start = $cgi->param('startDate');
    my $end = $cgi->param('endDate');
    my $type2 = $cgi->param('type2');
    my @users = $cgi->param('user');
    $data = Graph::CreateReviewerGraph($crms, $type2, $start, $end, @users);
  }
  elsif ($c == 11) { $data = Graph::CreateProgressGraph($crms); }
}
else
{
  $data = $crms->CreateExportData($year);
}

if ( $data eq '') { print $cgi->header( -status => "400" ); }
if (ref($data))
{
  my $json = JSON::XS->new->encode($data);
  print $cgi->header(-type => 'application/json', -charset => 'utf-8');
  print $json;
}
else
{
  print $cgi->header(-type => 'text/plain', -charset => 'utf-8');
  print $data;
}
