#!/usr/bin/perl

use strict;

BEGIN {
  die "SDRROOT environment variable not set" unless defined $ENV{'SDRROOT'};
  use lib $ENV{'SDRROOT'} . '/crms/cgi';
}

use CGI;
use JSON::XS;

use CRMS;

my $cgi  = new CGI;
my $crms = CRMS->new(cgi => $cgi);
my $year = $cgi->param('y');
my $data = $crms->CreateExportData($year);

print $cgi->header(-type => 'text/plain', -charset => 'utf-8');
print $data;
