#!/usr/bin/perl

use strict;
use FindBin;
use lib $FindBin::Bin;
use CGI;
use CRMS;
use Inserts;
use JSON::XS;

my $cgi  = new CGI;
my $sys  = $cgi->param('sys') || 'crms';
my $crms = CRMS->new(cgi => $cgi,
                     sys => $sys);
my $ins = Inserts->new(crms => $crms);
my $id = $cgi->param('id');
my $user = $cgi->param('user');
my $totals = $cgi->param('totals');
my $data = '';
if (defined $totals && $totals == 1)
{
  $data = $ins->GetTotalsData($id, $user);
}
else
{
  $data = $ins->GetInsertsData($id, $user);
}
my $json = JSON::XS->new->encode($data);
print $cgi->header(-type => 'application/json', -charset => 'utf-8');
print $json;
