#!/usr/bin/perl

my ($root_dir);
BEGIN 
{ 
  $root_dir = $ENV{'DLXSROOT'};
  $root_dir = $ENV{'SDRROOT'} unless $root_dir;
}

use strict;
use CGI;
use CRMS;
use Inserts;
use JSON::XS;

my $cgi  = new CGI;
my $sys  = $cgi->param('sys') || 'crms';
my $pdb = $cgi->param('pdb');
my $tdb = $cgi->param('tdb');
my $crms = CRMS->new(sys     => $sys,
                     verbose => 0,
                     pdb     => $pdb,
                     tdb     => $tdb);

my $ins = Inserts->new(crms => $crms);
my $id = $cgi->param('id');
my $user = $cgi->param('user');
my $totals = $cgi->param('totals');
my $data = '';
if (defined $totals && $totals == 1)
{
  $data = $ins->GetTotalsData($id, $user);
}
else
{
  $data = $ins->GetInsertsData($id, $user);
}
my $json = JSON::XS->new->encode($data);
print $cgi->header(-type => 'application/json', -charset => 'utf-8');
print $json;
