#!/usr/bin/perl

use strict;

BEGIN {
  die "SDRROOT environment variable not set" unless defined $ENV{'SDRROOT'};
  use lib $ENV{'SDRROOT'} . '/crms/cgi';
}

use CGI;

use CRMS;

my $cgi  = new CGI;
my $sys =  $cgi->param('sys') || 'crms';
my $crms = CRMS->new(cgi => $cgi,
                     sys => $sys);
my $id  = $cgi->param('id');
my $date = $crms->GetRenDate($id);

if ($date eq '') { print $cgi->header( -status => "400" ); }
else
{
  print CGI::header(-type => 'text/plain', -charset => 'utf-8');
  print $date;
}
