#!/usr/bin/perl

use strict;
use FindBin;
use lib $FindBin::Bin;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $sys =  $cgi->param('sys') || 'crms';
my $crms = CRMS->new(cgi => $cgi,
                     sys => $sys,
                     pdb => $cgi->param('pdb'),
                     tdb => $cgi->param('tdb'));
my $id  = $cgi->param('id');
my $date = $crms->GetRenDate($id);

if ($date eq '') { print $cgi->header( -status => "400" ); }
else
{
  print CGI::header(-type => 'text/plain', -charset => 'utf-8');
  print $date;
}
