#!/usr/bin/perl

use strict;

BEGIN {
  die "SDRROOT environment variable not set" unless defined $ENV{'SDRROOT'};
  use lib $ENV{'SDRROOT'} . '/crms/cgi';
  use lib $ENV{'SDRROOT'} . '/crms/lib';
}

use CGI;
use JSON::XS;

use CRMS;
use CRMS::RightsPredictor;
use Metadata;

my $cgi = new CGI;
my $id = $cgi->param('id');
my $year = $cgi->param('year');
my $is_pub = $cgi->param('is_pub');
my $is_crown = $cgi->param('is_crown');
my $crms = CRMS->new(cgi => $cgi);

my $record = Metadata->new('id' => $id);
my $rp = CRMS::RightsPredictor->new(record => $record);
my $data = $rp->rights($year, $is_pub, $is_crown);
$data->{desc} = join(', ', @{$data->{desc}});
if ($data->{attr} && $data->{reason}) {
  my $sql = 'SELECT r.id FROM rights r INNER JOIN attributes a ON r.attr=a.id'.
            ' INNER JOIN reasons rs ON r.reason=rs.id'.
            ' WHERE a.name=? AND rs.name=?';
  my $rights_id = $crms->SimpleSqlGet($sql, $data->{attr}, $data->{reason});
  $data->{rights_id} = $rights_id;
}

print CGI::header(-type => 'application/json', -charset => 'utf-8');
my $json = JSON::XS->new->encode($data);
print $json;
