#!/usr/bin/perl

use strict;
use FindBin;
use lib $FindBin::Bin;
use CGI;
use CRMS;
use Inserts;
use JSON::XS;

my $cgi = new CGI;
my $sys = $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(cgi => $cgi,
                     sys => $sys,
                     pdb => $cgi->param('pdb'),
                     tdb => $cgi->param('tdb'));

my $ins = Inserts->new(crms => $crms);
if ($cgi->param('requeue'))
{
  if ($crms->IsUserAdmin())
  {
    my $id = $cgi->param('id');
    my $user = $cgi->param('user');
    $ins->Requeue($id, $user);
  }
  else
  {
    $crms->SetError('Action not allowed.');
  }
}
else
{
  $ins->ConfirmInserts($cgi);
}
my $err = $crms->GetErrors();
if (scalar @{$err})
{
  $crms->Note("Warning: $_\n") for @{$crms->GetErrors()};
  print $cgi->header('text/html','500 Internal server error');
  print "Warning: $_\n" for @{$crms->GetErrors()};
}
else
{
  print $cgi->header;
}
