use crms;

/*FIXME: final `report` field is going away, should be simple find/replace */

LOCK TABLES `institutions` WRITE;
/*!40000 ALTER TABLE `institutions` DISABLE KEYS */;
INSERT INTO `institutions` VALUES
  (1,'University of Michigan','Michigan','umich.edu',1),
  (3,'Indiana University','Indiana','iu.edu',1),
  (5,'University of Wisconsin-Madison','Wisconsin','wisc.edu',1),
  (7,'University of Minnesota','Minnesota','umn.edu',1),
  (9,'Columbia University','Columbia','columbia.edu',1),
  (11,'Princeton University','Princeton','princeton.edu',1),
  (13,'Northwestern University','Northwestern','northwestern.edu',1),
  (15,'Stanford University','Stanford','stanford.edu',1),
  (17,'McGill University','McGill','mcgill.ca',1),
  (19,'Penn State University','Penn State','psu.edu',1),
  (21,'Johns Hopkins University','JHU','jhu.edu',1),
  (23,'Cornell University','Cornell','cornell.edu',0),
  (25,'University of North Carolina at Chapel Hill','UNC Chapel Hill','unc.edu',0),
  (27,'University of Arizona','Arizona','arizona.edu',0),
  (29,'Amherst College','Amherst','amherst.edu',0),
  (31,'Ohio State University','Ohio State','osu.edu',0),
  (33,'Boston College','Boston','bc.edu',0),
  (35,'DePaul University','DePaul','depaul.edu',0),
  (37,'University of Chicago','Chicago','uchicago.edu',0),
  (39,'Michigan State University','Michigan State','msu.edu',0),
  (41,'University of Massachusetts Amherst','UMass Amherst','umass.edu',0),
  (43,'University of Illinois','UIUC','illinois.edu',0),
  (45,'New York University','New York','nyu.edu',0),
  (47,'Lafayette College','Lafayette','lafayette.edu',0),
  (49,'University of Pittsburgh','Pitt','pitt.edu',0),
  (51,'University of Florida','Florida','ufl.edu',0),
  (53,'University of Mississippi','Mississippi','olemiss.edu',0),
  (55,'Texas A&M University','Texas A&M','tamu.edu',0),
  (57,'UCLA','UCLA','ucla.edu',0),
  (59,'University of Pennsylvania','Pennsylvania','upenn.edu',0),
  (61,'University of Tennessee Knoxville','UT Knoxville','utk.edu',0),
  (63,'Wake Forest University','Wake Forest','wfu.edu',0),
  (65,'University of Virginia','Virginia','virginia.edu',0),
  (67,'Georgia State University','GSU','gsu.edu',0),
  (69,'University of California Santa Cruz','UCSC','ucsc.edu',0),
  (71,'Washington State University','Washington State','wsu.edu',0),
  (73,'Temple University','Temple','temple.edu',0),
  (74,'Texas State University','Texas State','txstate.edu',0),
  (76,'University of Houston','Houston','uh.edu',0),
  (78,'University of California San Diego','UCSD','ucsd.edu',0),
  (79,'Duke University','Duke','duke.edu',0),
  (81,'California Digital Library','CDL','ucop.edu',0),
  (83,'University of Notre Dame','Notre Dame','nd.edu',0),
  (85,'UCSF','UCSF','ucsf.edu',0),
  (87,'Baylor University','Baylor','baylor.edu',0),
  (89,'UC Irvine','UC Irvine','uci.edu',0),
  (91,'Dartmouth College','Dartmouth','dartmouth.edu',0),
  (93,'University of Maryland','Maryland','umd.edu',0),
  (94,'University of Alberta','Alberta','ualberta.ca',0),
  (96,'McMaster University','McMaster','mcmaster.ca',0),
  (98,'University of Kentucky','Kentucky','uky.edu',0),
  (100,'University of British Columbia','UBC','ubc.ca',0),
  (102,'University of Texas at San Antonio','UTSA','utsa.edu',0),
  (103,'Queen\'s University','Queen\'s','queensu.ca',0),
  (104,'University of Oklahoma','Oklahoma','ou.edu',0),
  (106,'West Virginia University','W Virginia','wvu.edu',0);
/*!40000 ALTER TABLE `institutions` ENABLE KEYS */;
UNLOCK TABLES;
