# For settings and credentials related to the CRMS database, see db.yml
ht_db_user: mdp-lib
ht_db_password: mdp-lib
jira_user: crms
jira_password: crms
data_api_access_key: crms
data_api_secret_key: crms
