db_user: crms
db_password:
  development: crms
  training: crms_training
  production: crms_production
ht_db_user: mdp-lib
ht_db_password:
  development: mdp-lib
  training: mdp-lib
  production: mdp-lib
jira_user: crms
jira_password: crms
