#!/l/local/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;
use Template;
use POSIX;

my $user = $ENV{'REMOTE_USER'};
my $cgi  = new CGI;
my $crms = CRMS->new(
        logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
        configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
        verbose      =>   0,
        root         =>   $DLXSROOT,
        dev          =>   $DLPS_DEV,
        user         =>   $user,
        );

if  (  $cgi->param('p') eq 'Logout' )  
{

  #Remove all alias users for this user:
  $crms->ChangeAliasUserName($user, '');

  # change 'central' to the url of your weblogin server.
  my $central = "https://weblogin.umich.edu/cgi-bin/logout";
  my $query_string = "";
  
  # expire and nullify service cookie
  print( "Set-Cookie: $ENV{ COSIGN_SERVICE }=null; path=/; expires=Wednesday, 27-Jan-77 00:00:00 GMT; secure\n" );
  
  if ( $ENV{ QUERY_STRING } =~ m|^(https?://.*)$| ) {
    $query_string = "?$1";
  }

  # perform any local cleanup here
  
  # redirect to central weblogin server
  print( "Location: $central$query_string\n\n" );
  
  exit( 0 );

}


my $new_user = $crms->GetAliasUserName( $user );  
if ( ( $new_user ) )
{
  $user = $new_user;

  $crms = CRMS->new(
	logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
        configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
        verbose      =>   0,
        root         =>   $DLXSROOT,
        dev          =>   $DLPS_DEV,
        user         =>   $user,
        );
}
elsif  (  $cgi->param('changeuser') == 1 )  
{
  my $new_user = $cgi->param('newuser');
  $crms->ChangeAliasUserName($user, $new_user);  
  $user = $new_user;

  $crms = CRMS->new(
	logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
        configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
        verbose      =>   0,
        root         =>   $DLXSROOT,
        dev          =>   $DLPS_DEV,
        user         =>   $user,
        );
}


if ( ! $user || ! $ENV{'HTTPS'} ) 
{
    print $cgi->redirect( "https://$ENV{'HTTP_HOST'}$ENV{'SCRIPT_NAME'}" );
    exit;
}

## config options for TT
my $config = 
{
    INCLUDE_PATH => '.',
    INTERPOLATE  => 1,     ## expand "$var" in plain text
    POST_CHOMP   => 1,     ## cleanup whitespace
    EVAL_PERL    => 1,     ## evaluate Perl code blocks
};

## make sure user known
if ( ! $crms->GetUserName($user) )
{
    print $cgi->header( -status => "403 Forbidden" ) .
          "<h2>Forbidden</h2>";
    exit;
}

my $tt   = Template->new( $config );
my $vars = {
    title     => "CRMS",
    crms      => $crms,
    cgi       => $cgi,
    user      => $user,
    yesterday => POSIX::strftime("%Y-%m-%d %H:%M:%S", localtime(time-86400))
};

## the template page (tt) is called based on the CGI 'p' param (ex editReviews -> editReviews.tt)
## the default is home.tt in case a tt is not found
my $page  = $cgi->param('p');
my $input = $page . ".tt";
if ( ! -f $input ) { $input = "home.tt"; }

## print $cgi->header( -charset => 'iso-8859-1', "cache-control" => 'private' );
print $cgi->header( -charset => 'utf-8', "cache-control" => 'private' );
$tt->process($input, $vars) || die $tt->error();

