#!/l/local/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;
use Template;
use POSIX;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};

if ( ! $user || ! $ENV{'HTTPS'} ) 
{
    print $cgi->redirect( "https://$ENV{'HTTP_HOST'}$ENV{'SCRIPT_NAME'}" );
    exit;
}

my $page  = $cgi->param('p');
my $input = $page . ".tt";
if ( ! -f $input ) { $input = "home.tt"; }

## config options for TT
my $config = 
{
    INCLUDE_PATH => '.',
    INTERPOLATE  => 1,     ## expand "$var" in plain text
    POST_CHOMP   => 1,     ## cleanup whitespace
    EVAL_PERL    => 1,     ## evaluate Perl code blocks
};

my $tt    = Template->new( $config );
my $vars  = 
{
    title => "CRMS",
    crms  => CRMS->new(
        logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
        configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
        verbose      =>   1,
        root         =>   $DLXSROOT,
        dev          =>   $DLPS_DEV,
        user         =>   $user,
    ),
    cgi       => $cgi,
    user      => $user,
    yesterday => POSIX::strftime("%Y-%m-%d %H:%M:%S", localtime(time-86400))
};

print $cgi->header( -charset => 'iso-8859-1', "cache-control" => 'private' );
$tt->process($input, $vars) || die $tt->error();

