#!/usr/bin/perl

my $DLXSROOT;
BEGIN
{
  $DLXSROOT = $ENV{'DLXSROOT'};
}

use strict;
use CGI;
use CRMS;
use CRI;
use JSON::XS;

my $cgi = new CGI;
my $sys = $cgi->param('sys') || 'crms';
my $pdb = $cgi->param('pdb');
my $tdb = $cgi->param('tdb');
my $crms = CRMS->new(logFile => "$DLXSROOT/prep/c/crms/log_getReviewInfo.txt",
                     sys     => $sys,
                     verbose => 0,
                     root    => $DLXSROOT,
                     pdb     => $pdb,
                     tdb     => $tdb);

my $cri = CRI->new(crms => $crms);
my $id = $cgi->param('id');
my $data = $cri->GetCRIInfo($id) || '';
my $json = JSON::XS->new->encode($data);
print $cgi->header(-type => 'application/json', -charset => 'utf-8');
print $json;
