#!/l/local/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};
my $crms = CRMS->new(logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
                     configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
                     verbose      =>   0,
                     root         =>   $DLXSROOT,
                     dev          =>   $DLPS_DEV,
                     user         =>   $user);

my $type = $cgi->param('type');
my $data = '';
my $c = $cgi->param('c'); # Class or cumulative
if ($type eq 'graph')
{
  my $start = $cgi->param('startDate');
  my $end = $cgi->param('endDate');
  if ($c == 3) { $data = $crms->CreateExportStatusGraph(); }
  else { $data = $crms->CreateExportGraph($c, $start, $end); }
}
else
{
  $data = $crms->CreateExportData("\t",$c);
}

if ( $data eq '' ) { print $cgi->header( -status => "400" ); }
else
{
    print $cgi->header(-type => 'text/plain', -charset => 'utf-8');
    print $data;
}
