#!/usr/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};
my $sys =  $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile   =>   "$DLXSROOT/prep/c/crms/log_review.txt",
                     sys       =>   $sys,
                     verbose   =>   0,
                     root      =>   $DLXSROOT,
                     dev       =>   $DLPS_DEV,
                     user      =>   $user);

my $type = $cgi->param('type');
my $data = '';
my $c = $cgi->param('c'); # Class or cumulative
my $start = $cgi->param('startDate');
my $end = $cgi->param('endDate');
my $priority = $cgi->param('priority');
my $percent = $cgi->param('percent');
if ($type eq 'graph')
{
  my $monthly = $cgi->param('monthly');
  my $title = $cgi->param('title');
  if ($c == 3) { $data = $crms->CreateDeterminationsBreakdownGraph($start, $end, $monthly, $title, $percent); }
  else { $data = $crms->CreateExportGraph($c, $start, $end, undef, $priority); }
}
else
{
  $data = $crms->CreateExportData("\t", $c, 1, $start, $end);
}

if ( $data eq '' ) { print $cgi->header( -status => "400" ); }
else
{
  print $cgi->header(-type => 'text/plain', -charset => 'utf-8');
  print $data;
}
