#!/usr/bin/perl

my $DLXSROOT;
BEGIN
{
  $DLXSROOT = $ENV{'DLXSROOT'};
}

use strict;
use CGI;
use CRMS;
use Inserts;
use JSON::XS;

my $cgi  = new CGI;
my $sys  = $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile => "$DLXSROOT/prep/c/crms/log_getInsertsInfo.txt",
                     sys     => $sys,
                     verbose => 0,
                     root    => $DLXSROOT,
                     pdb     => $cgi->param('pdb'),
                     tdb     => $cgi->param('tdb'));

my $ins = Inserts->new(crms => $crms);
my $id = $cgi->param('id');
my $user = $cgi->param('user');
my $totals = $cgi->param('totals');
my $data = '';
if (defined $totals && $totals == 1)
{
  $data = $ins->GetTotalsData($id, $user);
}
else
{
  $data = $ins->GetInsertsData($id, $user);
}
my $json = JSON::XS->new->encode($data);
print $cgi->header(-type => 'application/json', -charset => 'utf-8');
print $json;
