#!/usr/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;
use Inserts;
use JSON::XS;

my $cgi  = new CGI;
my $sys  = $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile => "$DLXSROOT/prep/c/crms/log_getReviewInfo.txt",
                     sys     => $sys,
                     verbose => 0,
                     root    => $DLXSROOT,
                     dev     => $DLPS_DEV,
                     pdb     => $cgi->param('pdb'));

my $ins = Inserts->new(crms => $crms);
my $id = $cgi->param('id');
my $user = $cgi->param('user');
my $data = $ins->GetInsertsData($id, $user);
my $json = JSON::XS->new->utf8->encode($data);
print $cgi->header('application/json');
print $json;
