#!/usr/bin/perl

my ($root_dir);
BEGIN 
{ 
  $root_dir = $ENV{'DLXSROOT'};
  $root_dir = $ENV{'SDRROOT'} unless $root_dir;
}

use strict;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $sys =  $cgi->param('sys') || 'crms';
my $pdb = $cgi->param('pdb');
my $tdb = $cgi->param('tdb');
my $crms = CRMS->new(sys     => $sys,
                     verbose => 0,
                     pdb     => $pdb,
                     tdb     => $tdb);
my $id  = $cgi->param('id');
my $date = $crms->GetRenDate($id);

if ($date eq '') { print $cgi->header( -status => "400" ); }
else
{
  print $cgi->header();
  print $date;
}
