#!/usr/bin/perl

my $DLXSROOT;
BEGIN
{
  $DLXSROOT = $ENV{'DLXSROOT'};
}

use strict;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $id   = $cgi->param('id');
my $sys =  $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile => $DLXSROOT. '/prep/c/crms/log_getRenewalDate.txt',
                     sys     => $sys,
                     verbose => 0,
                     root    => $DLXSROOT,
                     pdb     => $cgi->param('pdb'),
                     tdb     => $cgi->param('tdb'));

my $date = $crms->GetRenDate( $id );

if ($date eq '') { print $cgi->header( -status => "400" ); }
else
{
  print $cgi->header();
  print $date;
}
