#!/usr/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;
use JSON::XS;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};
my $sys  = $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile  =>   "$DLXSROOT/prep/c/crms/log_getReviewInfo.txt",
                     sys      =>   $sys,
                     verbose  =>   0,
                     root     =>   $DLXSROOT,
                     dev      =>   $DLPS_DEV,
                     user     =>   $user);

my $id = $cgi->param('id');
my $user = $cgi->param('user');
my $sql = 'SELECT attr,reason,note,category,renNum,renDate FROM reviews WHERE id=? AND user=?';
my $row = $crms->SelectAll($sql, $id, $user)->[0];
my %data;
$data{'rights'} = $crms->GetCodeFromAttrReason($row->[0], $row->[1]);
# If the rights attr is not und (5) then run a rights prediction
if ($row->[0] != $crms->TranslateAttr('und'))
{
  $data{'rights'} = $crms->PredictRights($id, $row->[5], $row->[4],
                                         $crms->TolerantCompare($row->[3],
                                                                'Crown Copyright'));
}
$data{'note'} = $row->[2];
$data{'category'} = $row->[3];
$data{'renNum'} = $row->[4];
$data{'renDate'} = $row->[5];
$data{'sql'} = $sql;
print $cgi->header();
my $json = JSON::XS->new->utf8->encode(\%data);
print $json;

