#!/l/local/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};
my $id   = $cgi->param('id');
my $crms = CRMS->new(logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
                     configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
                     verbose      =>   0,
                     root         =>   $DLXSROOT,
                     dev          =>   $DLPS_DEV,
                     user         =>   $user);

my $date = $crms->GetRegDate( $id );

if ( $date eq "" ) { print $cgi->header( -status => "400" ); }
else
{
    print $cgi->header();
    print $date;
}
