#!/l/local/bin/perl

my $DLXSROOT;
my $DLPS_DEV;
BEGIN 
{ 
    $DLXSROOT = $ENV{'DLXSROOT'}; 
    $DLPS_DEV = $ENV{'DLPS_DEV'}; 
    ## unshift ( @INC, $ENV{'DLXSROOT'} . "/crms/cgi" );
}

use strict;
use CRMS;
use CGI;

my $crms = CRMS->new(
    logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
    configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
    verbose      =>   0,
    root         =>   $DLXSROOT,
    dev          =>   $DLPS_DEV,
);

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};

if ( $user eq "" ) { Redirect(); }

my $userName = $crms->GetUserName( $user );
my @types    = $crms->GetUserTypes( $user );

print qq{Content-type: text/html

<html>
  <head>
    <title>CRMS</title>
    <link rel="stylesheet" type="text/css" href="/c/crms/css/review.css" />
  </head>
  <body onLoad="setTimeout('redir()', 1000)">

  <h3>Hello $userName</h3> 
  <hr width="25%" align="left"/>
      <div>|| <a href="/cgi/c/crms/home">home</a> || 
      <a href="/cgi/c/crms/editReviews">edit reviews</a> || };
if ( grep /1/, @types ) { print qq{<a href="/cgi/c/crms/review">review</a> || }; }
if ( grep /2/, @types ) { print qq{<a href="/cgi/c/crms/menu">expert review</a> || }; }
if ( grep /3/, @types ) { print qq{<a href="/cgi/c/crms/admin">admin menu</a> || }; }

print qq{</div></body></html>};

## ============================================================================ ##
##
## ============================================================================ ##

sub Redirect
{
    print qq{Content-type: text/html

<html>
  <head>
    <title>CRMS</title>
    <script type="text/javascript">
    <!--
    function Redir(){
        newURL = "https://" + window.location.host + "/cgi/c/crms/home";
        window.location = newURL;
    }
    //-->
    </script>
  </head> 
  <body onLoad="setTimeout('Redir()', 0)"></body>
</html>};
    exit;
}

