#!/l/local/bin/perl

my $DLXSROOT;
my $DLPS_DEV;
BEGIN 
{ 
    $DLXSROOT = $ENV{'DLXSROOT'}; 
    $DLPS_DEV = $ENV{'DLPS_DEV'}; 
    ## unshift ( @INC, $ENV{'DLXSROOT'} . "/crms/cgi" );
}

use strict;
use CRMS;
use CGI;

my $crms = CRMS->new(
    logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
    configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
    verbose      =>   0,
    root         =>   $DLXSROOT,
    dev          =>   $DLPS_DEV,
);

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};

if ( $user eq "" ) { Redirect(); }

my @types = $crms->GetUserTypes( $user );
if ( grep /1/, @types )
{
    $crms->UnlockItem( $cgi->param('barcode') );
    print qq{Content-type: text/html

    <html>
      <head>
        <title>CRMS</title>
        <script type="text/javascript">
        <!--
        function redir(){
            window.location = "/cgi/c/crms/home"
        }
        //-->
        </script>
      </head>
      <body onLoad="setTimeout('redir()', 500)">\n};
    
      print qq{<p>Item checked in. Going to home page...</a></p>};

      ## the end
    print "</body></html>";
}

sub Redirect
{
    print qq{Content-type: text/html

<html>
  <head>
    <title>CRMS</title>
    <script type="text/javascript">
    <!--
    function Redir(){
        newURL = "https://" + window.location.host + "/cgi/c/crms/home";
        window.location = newURL;
    }
    //-->
    </script>
  </head> 
  <body onLoad="setTimeout('Redir()', 0)"></body>
</html>};
    exit;
}

