#!/usr/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};
my $id   = $cgi->param('id');
my $year = $cgi->param('year');
my $sys =  $cgi->param('sys');
my $pub =  $cgi->param('pub');
my $crown = $cgi->param('crown');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile  =>   "$DLXSROOT/prep/c/crms/log_review.txt",
                     sys      =>   $sys,
                     verbose  =>   0,
                     root     =>   $DLXSROOT,
                     dev      =>   $DLPS_DEV,
                     user     =>   $user);

my $n = $crms->PredictRights($id, $year, $pub, $crown);

if ($n !~ /\d+/) { print $cgi->header( -status => "400" ); }
else
{
  print $cgi->header();
  print $n;
}
