#!/usr/bin/perl

my ($root_dir);
BEGIN 
{ 
  $root_dir = $ENV{'DLXSROOT'};
  $root_dir = $ENV{'SDRROOT'} unless $root_dir;
}

use strict;
use CGI;
use CRMS;

my $cgi    = new CGI;
my $id     = $cgi->param('id');
my $year   = $cgi->param('year');
my $sys    = $cgi->param('sys');
my $ispub  = $cgi->param('ispub');
my $crown  = $cgi->param('crown');
my $pub    = $cgi->param('pub');
my $doyear = $cgi->param('doyear');
my $readable = $cgi->param('readable');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(sys     => $sys,
                     verbose => 0,
                     pdb     => $cgi->param('pdb'),
                     tdb     => $cgi->param('tdb'));

my $n;
if (defined $doyear)
{
  $n = $crms->PredictLastCopyrightYear($id, $year, $ispub, $crown, undef, \$pub);
  my $r = $crms->TranslateRights($crms->PredictRights($id, $year, $ispub, $crown, undef, $pub));
  if (defined $n)
  {
    $n++;
    if (defined $r && $r =~ /gatt$/)
    {
      $n = 95 + ((defined $pub)? $pub:$crms->GetPubDate($id));
      $n .= ' (GATT)';
    }
  }
  else
  {
    $n = 'unknown';
  }
}
else
{
  #if (defined $pub && $pub =~ m/^(\d+)-(\d+)$/)
  #{
  #  my ($pub1, $pub2) = ($1, $2);
  #  my $r1 = $crms->PredictRights($id, $year, $ispub, $crown, $pub1);
  #  my $r2 = $crms->PredictRights($id, $year, $ispub, $crown, $pub2);
  #  $n = $r1 if $crms->TolerantCompare($r1, $r2);
  #}
  $n = $crms->PredictRights($id, $year, $ispub, $crown, undef, $pub) unless defined $n;
}
print $cgi->header();
if ($readable && $n)
{
  my $ref = $crms->SelectAll("SELECT attr,reason FROM rights WHERE id=?", $n);
  my $pa = $crms->TranslateAttr($ref->[0]->[0]);
  my $pr = $crms->TranslateReason($ref->[0]->[1]);
  $n = $pa . '/' . $pr;
}
print $n if defined $n;
