#!/usr/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;

my $cgi    = new CGI;
my $user   = $ENV{'REMOTE_USER'};
my $id     = $cgi->param('id');
my $year   = $cgi->param('year');
my $sys    = $cgi->param('sys');
my $ispub  = $cgi->param('ispub');
my $crown  = $cgi->param('crown');
#my $pub    = $cgi->param('pub');
my $doyear = $cgi->param('doyear');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile  =>   "$DLXSROOT/prep/c/crms/log_review.txt",
                     sys      =>   $sys,
                     verbose  =>   0,
                     root     =>   $DLXSROOT,
                     dev      =>   $DLPS_DEV,
                     user     =>   $user);
my $n;
if (defined $doyear)
{
  my $pub;
  $n = $crms->PredictLastCopyrightYear($id, $year, $ispub, $crown);
  my $r = $crms->TranslateRights($crms->PredictRights($id, $year, $ispub, $crown, undef, \$pub));
  if (defined $n)
  {
    $n++;
    if (defined $r && $r =~ /gatt$/)
    {
      $n = 95 + ((defined $pub)? $pub:$crms->GetPubDate($id));
      $n .= ' (GATT)';
    }
  }
  else
  {
    $n = 'unknown';
  }
}
else
{
  #if (defined $pub && $pub =~ m/^(\d+)-(\d+)$/)
  #{
  #  my ($pub1, $pub2) = ($1, $2);
  #  my $r1 = $crms->PredictRights($id, $year, $ispub, $crown, $pub1);
  #  my $r2 = $crms->PredictRights($id, $year, $ispub, $crown, $pub2);
  #  $n = $r1 if $crms->TolerantCompare($r1, $r2);
  #}
  $n = $crms->PredictRights($id, $year, $ispub, $crown) unless defined $n;
}
print $cgi->header();
print $n if defined $n;
