#!/l/local/bin/perl

my $DLXSROOT;
my $DLPS_DEV;
BEGIN 
{ 
    $DLXSROOT = $ENV{'DLXSROOT'}; 
    $DLPS_DEV = $ENV{'DLPS_DEV'}; 
    ## unshift ( @INC, $ENV{'DLXSROOT'} . "/crms/cgi" );
}

use strict;
use CRMS;
use CGI;

my $crms = CRMS->new(
    logFile      =>   "$DLXSROOT/prep/c/crms/log_review.txt",
    configFile   =>   "$DLXSROOT/bin/c/crms/crms.cfg",
    verbose      =>   0,
    root         =>   $DLXSROOT,
    dev          =>   $DLPS_DEV,
);

my $user      = $ENV{'REMOTE_USER'};
my $expert    = 0;
my $third     = 0;
my $cgi       = new CGI;
my $inBarcode = $cgi->param('barcode');


## if not logged in, send to login page
## if logged in, get status and send to review or other page
if ( $user eq "" ) 
{
    LoginRedirect();
    exit; 
}
else
{
    my @types = $crms->GetUserTypes( $user );

    if    ( grep /2/, @types ) { $expert = 1;        }
    if    ( grep /1/, @types ) { StartReviewing();   }
    elsif ( grep /3/, @types ) { AdminRedirect();    }
    else                       { NoAccessPage();     }
    exit;
}


sub StartReviewing
{
    ## start page
    print qq{Content-type: text/html

    <html>
      <head>
        <title>CRMS</title>
        <link rel="stylesheet" type="text/css" href="/c/crms/css/review.css" />
        <script type="text/javascript">
        <!--
        function popRenewLink(){
            document.forms['submitReview'].elements['renewLink'].value = document.getElementById('topFrame').src;
        }
        function popRights() {
            document.getElementById('ic').checked = true;
            document.getElementById('ren').checked = true;
        }
        function changeFrame(url) {
            document.getElementById("bFrame").src      = url;
            document.getElementById("bFrame").height   = "50%";
            document.getElementById("topFrame").height = "50%";
        }
        function changeFrame2(url) {
            document.getElementById("bFrame").src      = url;
            document.getElementById("bFrame").height   = "100%";
            document.getElementById("topFrame").height = "0%";
        }
        function openFrame() {
            document.getElementById("topFrame").height = "50%";
            document.getElementById("bFrame").height   = "50%";
        }
        function openFrame2() {
            document.getElementById("topFrame").height = "0%";
            document.getElementById("bFrame").height   = "100%";
        }
        function closeFrame() {
            document.getElementById("topFrame").height = "100%";
            document.getElementById("bFrame").height   = "0%";
        }
        function flipFrame() {
            topSize= (document.getElementById("bFrame").height);
            if ( topSize == "0%")
            {
                document.getElementById("topFrame").height = "50%";
                document.getElementById("bFrame").height   = "50%";
            }
            else
            {
                document.getElementById("topFrame").height = "100%";
                document.getElementById("bFrame").height   = "0%";
            }
        }
        function flipFrame2() {
            topSize= (document.getElementById("topFrame").height);
            if ( topSize == "100%")
            {
                document.getElementById("topFrame").height = "0%";
                document.getElementById("bFrame").height   = "100%";
            }
            else
            {
                document.getElementById("topFrame").height = "100%";
                document.getElementById("bFrame").height   = "0%";
            }    
        }

        function CopyToRenNum()
        {
            var clip = window.getSelection();
            window.clipboardData.setData( 'cb', window.getSelection() );
        }
        function PasteToRenNum()
        {
           // document.forms['submitReview'].elements['renNum'] = document.execCommand('Paste');
           // document.submitReview['renNum'].focus();
           // document.execCommand( 'Paste' );
           // alert( 'txt' );
           // document.submitReview['renNum'].value = document.execCommand('Paste');
           var txt = document.execCommand('Copy');
           alert( 'clip' );
           // document.submitReview['renNum'].value = window.clipboardData.getData();;
        }
        //-->
        </script>
      </head>
    <body>\n};

    my $barcode;
    ## if this user has something locked, pull that one up
    ## otherwise, get a new item to be reviewed

    if ( $inBarcode ne "" )
    { 
        if ( ! $crms->LockItem( $inBarcode, $user ) ) { fail( "One item at a time please." ); }
    }

    if ( $crms->HasLockedItem($user) ) { $barcode = $crms->GetLockedItem( $user );        }
    else                               { $barcode = $crms->GetNextItemForReview( $user ); }

    ## if ( $barcode eq "" ) { fail( "No barcode given"); }

    ## start body and NAV bar
    my $userName = $crms->GetUserName( $user );
    my $pub_date = $crms->GetPublDate( $barcode );
    my $author   = $crms->GetMarcDatafield( $barcode, "100", "a");
    my $title    = $crms->GetMarcDatafield( $barcode, "245", "a");
    my $regNum   = $crms->GetRegNum( $barcode );
    my $regDate  = $crms->GetRegDate( $regNum );
    my $normReg  = $crms->NormalizeRenewalId( $barcode );
    $third       = $crms->IsThirdReview( $barcode );

    my ($commPre, $comm) = $crms->GetReviewComment( $barcode, $user );

    ## links to PT, stanford DB search, or Mirlyn catalog
    my $encAuthor  = UrlEncode( $author );
    my $encTitle   = UrlEncode( $title );

    my $authorLink = "http://collections.stanford.edu/copyrightrenewals" . 
                     "/bin/search/advanced/process?clauseMapped(author)=$encAuthor";
    my $titleLink  = "http://collections.stanford.edu/copyrightrenewals" . 
                     "/bin/search/advanced/process?clauseMapped(title)=$encTitle";
    ## my $ptLink     = qq{https://babel.hathitrust.org/cgi/pt?id=$barcode} . 
    my $ptLink     = qq{https://santelli.dev.umdl.umich.edu/cgi/m/mdp/pt?skin=crms;id=$barcode} . 
                     qq{;page=root;view=image;size=75;seq=7;attr=1};
    my $catLink    = qq{http://mirlyn.lib.umich.edu/F?func=find-b&find_code=MDN} .
                     qq{&local_base=MIU01_PUB&request=$barcode};
    my $wCatLink   = qq{http://www.worldcat.org/search?qt=worldcat_org_bks&fq=dt%3Abks&q=$encTitle};
                     
    my $uscorLink  = qq{http://cocatalog.loc.gov/cgi-bin/Pwebrecon.cgi?DB=local&PAGE=First&Search_Arg=$encTitle};

    if ( $regNum )
    {
        $uscorLink = qq{http://cocatalog.loc.gov/cgi-bin/Pwebrecon.cgi?Search_Arg=$normReg&Search_Code=REGS&PAGE=First};
    }

    my $stanLink   = qq{http://collections.stanford.edu/copyrightrenewals/bin/search/simple/process?query=$regNum};

    print qq{<div class="divbody"><div class="divNav">
             <div class="navtop"> 
             <table width="100%">
               <tr>
                 <td align="left"   valign="top"><a href="/cgi/c/crms/logout?barcode=$barcode">home</a></td>
                 <td align="center" valign="top">Hello $userName</td>
                 <td align="right"  valign="top"><a href="/cgi/c/crms/logout?barcode=$barcode">logout</a></td>
               </tr>
             </table><hr />};

    print qq{<a href="$titleLink" target="topFrame">Stanford</a>   ||
             <a href="$ptLink"    target="topFrame" accesskey="h">HathiTrust</a> ||
             <a href="$catLink"   target="topFrame" accesskey="m">Mirlyn</a> || <br />

             <a href="$wCatLink"  target="topFrame">World Cat</a>   ||
             <a href="$uscorLink" target="topFrame">U.S. Copyright</a><br/>
 
             <hr />
             <strong>1/2: </strong><a href="javascript:changeFrame('$titleLink' )">ti</a> ||
                                   <a href="javascript:changeFrame('$authorLink')">au</a> ||
                                    <a href="javascript:flipFrame()"              >[x]</a>

             <hr />
             <strong>full: </strong><a href="javascript:changeFrame2('$titleLink')"  accesskey="t">ti</a> ||
                                    <a href="javascript:changeFrame2('$authorLink')" accesskey="a">au</a> ||
                                    <a href="javascript:flipFrame2()"                accesskey="x">[x]</a>

             <hr />
             <strong>ID:</strong> <tt>$barcode</tt></br>
             <strong>Title:</strong>  <a href="$titleLink"  target="bFrame">$title</a><br/>
             <strong>Author:</strong> <a href="$authorLink" target="bFrame">$author</a><br/>
             <strong>Pub Date:</strong> $pub_date <br/>};

    if ( $regNum ) 
    { 
        print qq{<strong>Renewal:      </strong><a href="$stanLink" target="topFrame">$regNum</a> ($regDate)<br/>}; 
    }

    ## bottom nav, review submission form
    print qq{</div><div class="navbottom">\n};

    print "<hr/>" . buildSubmitReviewForm( $barcode, $pub_date, $regNum, $regDate, $comm, $commPre );

    print qq{</div>\n};

    ## the frame (Stanford, HT, Cat...)
    print qq{</div>
        <div class="divFrame">
          <iframe width="100%" height="100%" id="topFrame" name="topFrame" src="$ptLink"></iframe>
          <iframe width="100%" height="0%"   id="bFrame"   name="bFrame"   src="$titleLink"></iframe>
        </div>
      </div>};

    ## the end
    print "</body></html>"; 
}

sub buildSubmitReviewForm
{
    my $id       = shift;
    my $date     = shift;
    my $regNum   = shift;
    my $regDate  = shift;
    my $comm     = shift;
    my $commPre  = shift;

    my $expertCheck  = buildExp();
    my $rightsReason = buildRightsReason( $crms->GetAttrReasonCode($id, $user) );
    my $commentPre   = buildCommPre( $commPre );

    my $html = qq{
      <form name="submitReview" action="/cgi/c/crms/submitReview">
        <input type="hidden" name="barcode" value="$id"> 
        <input type="hidden" name="user"    value="$user"> 
        <input type="hidden" name="date"    value="$date"> 
        <input type="hidden" name="confirm" value="1"> 

        <!--
        <strong>Rights: </string><a href="/c/crms/help.html#rights" target="_blank">?</a><br/>
        <input type="radio" id="pd"  name="rights" value="1" >PD (1)</input><br/>
        <input type="radio" id="ic"  name="rights" value="2" >IC (2)</input><br/>
        <input type="radio" id="und" name="rights" value="5">UND (5)</input><br/>
        <br/>
        <strong>Reason:</string> <a href="/c/crms/help.html#reason" target="_blank">?</a><br/>
        <input type="radio" id="ren"  name="reason" value="7">REN (7)</input><br/>
        <input type="radio" id="ncn"  name="reason" value="2">NCN (2)</input><br/>
        <input type="radio" id="nfi"  name="reason" value="8">NFI (8)</input><br/> 
        <input type="radio" id="cdpp" name="reason" value="9">CDPP (9)</input><br/> 
        <br/>
        -->

        $rightsReason
 
        <!--
        <strong>Rights/Reason: </string><a href="/c/crms/help.html#rights" target="_blank">?</a><br/>
        <input type="radio" id="1" name="rights" value="1" accesskey="1">pd/ncn (1)</input><br/>
        <input type="radio" id="2" name="rights" value="2" accesskey="2">pd/ren (2)</input><br/>
        <input type="radio" id="3" name="rights" value="3" accesskey="3">pd/cdpp (3)</input><br/>
        <input type="radio" id="4" name="rights" value="4" accesskey="4">ic/ren (4)</input><br/>
        <input type="radio" id="5" name="rights" value="5" accesskey="5">ic/cdpp (5)</input><br/>
        <input type="radio" id="6" name="rights" value="6" accesskey="6">und/nfi (6)</input><br/>
        -->
        <br/>

        <!--
        <Strong>Save Link to this Renewal:</strong>
        <input type="text"   name="renewLink" />
        <input type="button" value="save" onChange="popRenewLink()">
        <br/>
        -->

        <Strong>Copyright renewal ID: <a href="/c/crms/help.html#renewal" target="_blank">?</a></strong>
        <input type="text" name="renNum" value="$regNum"/>
        <br/>
        <Strong>Copyright renewal Date: <a href="/c/crms/help.html#renewal" target="_blank">?</a></strong>
        <input type="text" name="regDate" value="$regDate"/>
        <br/>


        <Strong>Publication date: <a href="/c/crms/help.html#publ" target="_blank">?</a></strong>
        <input type="text" name="cDate" value="$date"/>
        <br/>

        <!--
        <Strong>Copyright renewal date:</strong>
        <input type="text" name="renDate" />
        <br/>
        -->
        
        $expertCheck
 
        <input type="checkbox" name="flag" accesskey="f">Flag:</input> <a href="/c/crms/help.html#flag" target="_blank">?</a><br/>
        <br/>
        <strong>Comments: </string><a href="/c/crms/help.html#comment" target="_blank">?</a><br/>
        <!--
        <select name="commentPre">
          <option value="" selected="selected">none</option>
          <option value="Foreign"    >Foreign Pub</option>
          <option value="Missing"    >Missing</option>
          <option value="Collection" >Collection</option>
          <option value="Reprint"    >Reprint</option>
          <option value="Series"     >Series/Serial</option>
          <option value="Translation">Translation</option>
          <option value="Misc"       >Misc.</option>
        </select>
        -->
        $commentPre

        <textarea name="comment" cols="25" rows="3">$comm</textarea>

        <br/><br/>
        <input type="submit" value="Submit"> 
      </form>};

    return $html;
}

sub buildRightsReason
{
    my $select = shift;
    my $return = qq{<strong>Rights/Reason: </strong><a href="/c/crms/help.html#rights" } .
                 qq{ target="_blank">?</a><br/>};
    
    my %key = (1 => "pd/ncn", 2 => "pd/ren",  3 => "pd/cdpp",
               4 => "ic/ren", 5 => "ic/cdpp", 6 => "und/nfi" );
    foreach my $num ( 1..6 )
    {
        if ( $num eq $select )
        {
            $return .= qq|<input type="radio" id="$num" name="rights" value="$num" | .
                       qq|accesskey="$num" checked="checked">$key{$num} ($num)</input><br/>|;
        }
        else 
        {
            $return .= qq|<input type="radio" id="$num" name="rights" value="$num" | .
                       qq|accesskey="$num">$key{$num} ($num)</input><br/>|;
        }
    }

    return $return;
}

sub buildCommPre
{    
    my $select = shift;
    my $return = qq{<select name="commentPre">};

    my %key = ("Foreign"    => "Foreign Pub",   "Missing"     => "Missing",
               "Collection" => "Collection",    "Reprint"     => "Reprint",
               "Series"     => "Series/Serial", "Translation" => "Translation",
               "Misc"       => "Misc.",         ""            => "none");

    foreach ( sort keys %key )
    {
        if ( $_ eq $select )
        {
            $return .= qq|<option value="$_" selected="selected">$key{$_}</option>|;
        }
        else
        {
            $return .= qq|<option value="$_">$key{$_}</option>|;
        }
    }
    $return .= "</select>";

    return $return;
}

sub buildExp
{
    if ( ! $expert ) { return; }

    my $html;
    if ( $third )
    { 
        $html = qq{<input type="checkbox" name="exp" checked="checked">Final Determination</input>
                   <a href="/c/crms/help.html#final" target="_blank">?</a><br/>}; 
    }
    else
    {
        $html = qq{<input type="checkbox" name="exp">Final Determination</input>
                   <a href="/c/crms/help.html#ifinal" target="_blank">?</a><br/>};
    }
    return $html;
}

sub UrlEncode
{
    ## need to work on this...
    my $in = shift;
    $in =~ s, ,+,g;
    return $in
}

sub fail { print $_; exit; }

sub Redirect
{
    my $loc      = shift;
    my $msg      = shift;
    my $time     = shift;
    print qq{Content-type: text/html

    <html>
      <head>
        <title>CRMS</title>
        <script type="text/javascript">
        <!--
        function adminRedir(){
            newURL = "https://" + window.location.host + "/cgi/c/crms/admin";
            window.location = newURL;
        }
        function reviewRedir(){
            newURL = "https://" + window.location.host + "/" + window.location.pathname;
            window.location = newURL;
        }
        //-->
        </script>
      </head> };
    if ( $loc eq "review" ) { print qq{<body onLoad="setTimeout('reviewRedir()', $time)">\n}; }
    if ( $loc eq "admin" )  { print qq{<body onLoad="setTimeout('adminRedir()',  $time)">\n}; }

    print qq{<p>$msg</p>};

    ## the end
    print "</body></html>";
}

sub LoginRedirect { Redirect("review", "login redirect.", 0); }

sub AdminRedirect { Redirect("admin",  "admin redirect.", 0); }

sub NoAccessPage 
{ 
    print qq{Content-type: text/html

    <html>
      <head>
        <title>CRMS</title>
      </head>
      <body>
        <p>You do no appear to have sufficient permissions to access the CRMS review system.</p>
      </body>
    </html>};
}




