#!/usr/bin/perl

my ($DLXSROOT, $DLPS_DEV);
BEGIN { $DLXSROOT = $ENV{'DLXSROOT'}; $DLPS_DEV = $ENV{'DLPS_DEV'}; }

use strict;
use CGI;
use CRMS;
use Inserts;
use JSON::XS;

my $cgi  = new CGI;
my $user = $ENV{'REMOTE_USER'};
my $sys  = $cgi->param('sys');
$sys = 'crms' unless $sys;
my $crms = CRMS->new(logFile  =>   "$DLXSROOT/prep/c/crms/log_getReviewInfo.txt",
                     sys      =>   $sys,
                     verbose  =>   0,
                     root     =>   $DLXSROOT,
                     dev      =>   $DLPS_DEV,
                     user     =>   $user);

my $ins = Inserts->new(crms => $crms);

$ins->ConfirmInserts($cgi);
my $err = $crms->GetErrors();
if (scalar @{$err})
{
  $crms->Note("Warning: $_\n") for @{$crms->GetErrors()};
  print $cgi->header('text/html','500 Internal server error');
  print "Warning: $_\n" for @{$crms->GetErrors()};
}
else
{
  print $cgi->header;
}
