name: Build Latest from main

on:
  workflow_run:
    workflows: [ 'Run Tests']
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: hathitrust/github_actions/build@v1
        with:
          image: ghcr.io/${{ github.repository }}-unstable
          dockerfile: Dockerfile
          submodules: true
          tag: ${{ github.sha }}
          push_latest: true
          registry_token: ${{ github.token }}
