name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out including submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up tests
        run: |
          docker compose build
          docker compose run --rm test /htapps/babel/crms/bin/build.sh

      - name: Run tests
        run: docker compose run --rm test /htapps/babel/crms/scripts/test_and_cover.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
