name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out including private submodules
        uses: actions/checkout@v2
        with:
          # This should be a PAT that has read access to the private submodules
          # for this repository
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Build docker image
        run: docker compose --file docker-compose.test.yml build

      - name: Run tests
        run: docker compose --file docker-compose.test.yml run sut
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Report to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
